name: Deploy a GitHub Pages

on:
  [push, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Insertar API_KEY en el proyecto
      run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Deploy a GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./ 